name: Generate Index
on: [push] # 每次提交代码自动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: python generate_index.py
      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate index" && git push)
